spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lennuplaneerija
    username: kasutaja
    password: parool

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect


